### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ianlulu** [IanLulu/MyTetris#1]
will pick back up later need to focus on job hunting
left off on: https://youtu.be/N1ktYfszqnM?si=69aqSq-hSB2cmm9H&t=4530
- [ ] fix description & update readme in github repo and fix description in-game
- Repo readme reference: https://github.com/daniellevert/War-App
- [ ] change up the style. use as reference for design:
- [C++ video thumbnail](https://i.ytimg.com/vi/wVYKG_ch4yM/maxresdefault.jpg)
- [Reddit Tetris mobile post](https://preview.redd.it/1mpsucumve181.jpg?width=640&crop=smart&auto=webp&s=c5e2c23983d6be146cac49e9084f01ddec31e14b)
- [Nintendo Tetris 99](https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_2.0/c_scale,w_400/ncom/en_US/dlc/switch-dlc/tetris-99-dlc/rom-bundle/tetris-99-plus-big-block-dlc-plus-nintendo-switch-online-individual-membership-12-months/screenshot-gallery/screenshot05)
- [Tetris pixel font pause screen](https://d112y698adiu2z.cloudfront.net/photos/production/software_photos/001/555/977/datas/original.png)
- [ ] add a screen recording of gameplay
- screen recording/gif reference: https://stackoverflow.com/questions/28354217/how-can-you-record-your-screen-in-a-gif
- [ ] look into releasing the game on [itch.io](https://itch.io/updates/support-for-java-applets-added) (for demo purposes only)
- [ ] try implementing hard drop and hold functions
- &rarr; [hold example](https://github.com/jbens/Tetris/blob/master/Hold.java) & [hard drop example](https://www.gridbugs.org/reverse-engineering-nes-tetris-to-add-hard-drop/)
